
package com.ztw.platform.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPlatformOldWebService", targetNamespace = "http://ws.platform.ztw.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPlatformOldWebService {


    /**
     * 
     * @param resourceCode
     * @param json
     * @param urlCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ws.platform.ztw.com")
    @RequestWrapper(localName = "uploadObject", targetNamespace = "http://ws.platform.ztw.com", className = "com.ztw.platform.ws.UploadObject")
    @ResponseWrapper(localName = "uploadObjectResponse", targetNamespace = "http://ws.platform.ztw.com", className = "com.ztw.platform.ws.UploadObjectResponse")
    public String uploadObject(
            @WebParam(name = "resourceCode", targetNamespace = "http://ws.platform.ztw.com")
                    String resourceCode,
            @WebParam(name = "urlCode", targetNamespace = "http://ws.platform.ztw.com")
                    String urlCode,
            @WebParam(name = "json", targetNamespace = "http://ws.platform.ztw.com")
                    String json);

}
